name: Trigger AWS Deploy
on: [push]
jobs:
  build_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: up
        env:
          AWS_ACCESS_KEY_ID: \{\%\- raw \-\%\}$\{\%\- endraw \-\%\}
          AWS_SECRET_ACCESS_KEY: \{\%\- raw \-\%\}$\{\%\- endraw \-\%\}
        run: |
          yarn @11ty/eleventy
          aws s3 cp \
            --recursive \
            --acl public-read \
            --region ap-southeast-2 \ 
            ./_site/ [s3://www.weka.digital] # change it
          
